name: "MemeCLIP_Hateful"

data:
  dataset_name: "HatefulMemes"
  root_dir: "/home/rpisanu/Hateful/hateful_memes/data/"
  
  train_file: "/home/rpisanu/Hateful/hateful_memes/data/train.jsonl"
  
  val_file: "/home/rpisanu/Hateful/hateful_memes/data/dev.jsonl" 
  test_file: "/home/rpisanu/Hateful/hateful_memes/data/dev.jsonl"

  batch_size: 64
  num_workers: 4
  image_size: 224

model:
  name: "CLIP"
  clip_model: "ViT-L/14"
  hidden_dim: 512
  dropout: 0.5

training:
  max_epochs: 15
  learning_rate: 1e-4
  weight_decay: 1e-2
  checkpoint_dir: "./checkpoints/hateful_memes"
  log_dir: "./logs/hateful_memes"
